name: notepad
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  awesome_dialog: ^3.2.1
  fluttertoast: ^8.2.8
  group_list_view: ^1.1.1
  roundcheckbox: ^2.0.5
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/logo.png